# Generated by Django 3.2.4 on 2022-05-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('prenom', models.CharField(max_length=40)),
                ('tel', models.CharField(max_length=10)),
                ('mail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('besoin_eau', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PlanteZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_zone', models.IntegerField()),
                ('id_plante', models.IntegerField()),
                ('dernier_arr', models.DateTimeField()),
                ('prochain_arr', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_emp', models.IntegerField()),
                ('id_tech', models.IntegerField()),
                ('adresse', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('prenom', models.CharField(max_length=40)),
                ('tel', models.CharField(max_length=10)),
                ('mail', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicienZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_zone', models.IntegerField()),
                ('id_emp', models.IntegerField()),
                ('id_resp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('prenom', models.CharField(max_length=40)),
                ('tel', models.CharField(max_length=10)),
                ('mail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('adresse', models.CharField(max_length=200)),
                ('superficie', models.IntegerField()),
                ('public', models.BooleanField()),
                ('prix', models.BooleanField()),
                ('id_utilisateur', models.IntegerField()),
                ('picnic', models.BooleanField()),
                ('camping', models.BooleanField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
