# Generated by Django 3.2.4 on 2022-05-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_utilisateur', models.IntegerField()),
                ('id_admin', models.IntegerField()),
                ('type_demande', models.CharField(choices=[('Arroser', 'Arroser'), ('Planter', 'Planter')], max_length=50)),
                ('description', models.TextField()),
                ('jour', models.DateTimeField()),
                ('adresse', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='tache',
            old_name='id_emp',
            new_name='id_admin',
        ),
        migrations.RenameField(
            model_name='technicienzone',
            old_name='id_emp',
            new_name='id_tech',
        ),
    ]
