# Generated by Django 3.2.4 on 2022-05-21 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20220521_2041'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='Admin',
        ),
        migrations.AlterModelTable(
            name='demande',
            table='Demande',
        ),
        migrations.AlterModelTable(
            name='plante',
            table='Plante',
        ),
        migrations.AlterModelTable(
            name='plantezone',
            table='PlanteZone',
        ),
        migrations.AlterModelTable(
            name='tache',
            table='Tache',
        ),
        migrations.AlterModelTable(
            name='technicien',
            table='Technicien',
        ),
        migrations.AlterModelTable(
            name='technicienzone',
            table='TechnicienZone',
        ),
        migrations.AlterModelTable(
            name='utilisateur',
            table='Utilisateur',
        ),
        migrations.AlterModelTable(
            name='zone',
            table='Zone',
        ),
    ]
