# Generated by Django 3.2.4 on 2022-05-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20220522_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='image',
            field=models.ImageField(upload_to='Zone'),
        ),
    ]
