# Generated by Django 3.2.4 on 2022-05-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_zone_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='manger',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='zone',
            name='public',
            field=models.CharField(choices=[('Public', 'Public'), ('Prive', 'Prive')], max_length=50),
        ),
    ]
