# Generated by Django 3.2.4 on 2022-05-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20220522_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
