# Generated by Django 3.2.4 on 2022-05-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20220522_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='technicien',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='technicien',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='prenom',
        ),
        migrations.AddField(
            model_name='admin',
            name='id_utilisateur',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technicien',
            name='id_utilisateur',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='id_utilisateur',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technicien',
            name='department',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='image',
            field=models.ImageField(upload_to='prj_enc/main_app/static/images'),
        ),
    ]
