# Generated by Django 3.2.4 on 2022-05-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20220526_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='status',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
