# Generated by Django 3.2.4 on 2022-05-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_demande_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plante',
            name='besoin_eau',
        ),
        migrations.AlterField(
            model_name='zone',
            name='image',
            field=models.ImageField(upload_to='prj_enc/main_app/static/Zone'),
        ),
    ]
