# Generated by Django 3.2.4 on 2022-06-01 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20220530_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantezone',
            name='prochain_arr',
        ),
    ]
