# Generated by Django 3.2.4 on 2022-06-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_remove_plantezone_prochain_arr'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantezone',
            name='prochain_arr',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
