# Generated by Django 3.2.4 on 2022-06-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_plantezone_prochain_arr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='adresse',
        ),
        migrations.AddField(
            model_name='tache',
            name='id_zone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
