# Generated by Django 3.2.4 on 2022-06-01 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20220601_0508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tache',
            old_name='id_zone',
            new_name='id_pz',
        ),
    ]
