# Generated by Django 3.2.4 on 2022-06-01 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_rename_id_zone_tache_id_pz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='status',
        ),
    ]
