# Generated by Django 3.2.4 on 2022-06-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_tache_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
