# Generated by Django 3.2.4 on 2022-06-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_zone_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='id_admin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plante',
            name='image',
            field=models.ImageField(upload_to='prj_enc/main_app/static/Plante'),
        ),
    ]
